{{- if .Values.controller.template -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}-template
  namespace: {{ .Release.Namespace }}
data:
  haproxy.tmpl: |-
{{ .Values.controller.template | indent 4 }}
{{/* .Files.Get "haproxy.tmpl" | indent 4 */}}
{{- end }}
