apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  healthz-port: {{ .Values.controller.healthzPort | quote }}
{{- if and .Values.controller.metrics.enabled .Values.controller.metrics.embedded }}
  prometheus-port: {{ .Values.controller.metrics.port | quote }}
{{- end }}
  stats-port: {{ .Values.controller.stats.port | quote }}
{{- if .Values.controller.logs.enabled }}
  syslog-endpoint: "127.0.0.1:514"
{{- else if and .Values.controller.haproxy.enabled (not (hasKey .Values.controller.config "syslog-endpoint")) }}
  syslog-endpoint: "stdout"
  syslog-format: "raw"
{{- end }}
{{- if .Values.controller.config }}
  {{- tpl (toYaml .Values.controller.config) . | nindent 2 }}
{{- end }}
