{{- if eq .Values.controller.kind "DaemonSet" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    {{- toYaml .Values.controller.updateStrategy | nindent 4 }}
  minReadySeconds: {{ .Values.controller.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "haproxy-ingress.selectorLabels" . | nindent 6 }}
  template:
    {{- include "haproxy-ingress.controller.podTemplate" . | nindent 4 }}
{{- end }}
