{{- if and .Values.controller.metrics.enabled (or .Values.controller.stats.enabled .Values.controller.metrics.embedded) -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.controller.metrics.service.annotations }}
  annotations:
    {{- toYaml .Values.controller.metrics.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.serviceMonitor.enabled }}
    app.kubernetes.io/component: metrics
{{- end }}
  name: {{ include "haproxy-ingress.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.controller.metrics.service.clusterIP }}
  clusterIP: "{{ .Values.controller.metrics.service.clusterIP }}"
{{- end }}
{{- if .Values.controller.metrics.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.controller.metrics.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.controller.metrics.service.loadBalancerClass }}
  loadBalancerClass: "{{ .Values.controller.metrics.service.loadBalancerClass }}"
{{- end }}
{{- if .Values.controller.metrics.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.controller.metrics.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.controller.metrics.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.controller.metrics.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.controller.metrics.service.servicePort }}
      targetPort: metrics
    - name: ctrl-metrics
      port: {{ .Values.controller.metrics.service.serviceControllerPort }}
      targetPort: ctrl-metrics
  selector:
    {{- include "haproxy-ingress.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.controller.metrics.service.type }}"
{{- end }}
