{{- if or .Values.controller.template .Values.controller.templateFile -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}-template
  namespace: {{ .Release.Namespace }}
data:
  haproxy.tmpl: |
{{- if .Values.controller.templateFile -}}
{{ .Files.Get .Values.controller.templateFile | indent 4 }}
{{- else }}
{{ .Values.controller.template | indent 4 }}
{{- end }}
{{- end }}
