{{- if .Values.controller.template -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}-template
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "custom_template/haproxy.tmpl").AsConfig | indent 2 }}
{{- end }}
