{{- if and .Values.controller.serviceMonitor.enabled .Values.controller.metrics.enabled (or .Values.controller.stats.enabled .Values.controller.metrics.embedded) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if .Values.controller.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.controller.serviceMonitor.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.serviceMonitor.labels }}
    {{- toYaml .Values.controller.serviceMonitor.labels | nindent 4 }}
{{- end }}
  name: {{ include "haproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - honorLabels: {{ .Values.controller.serviceMonitor.honorLabels }}
    interval: {{ .Values.controller.serviceMonitor.interval }}
    path: /metrics
    port: metrics
    {{- if .Values.controller.serviceMonitor.params }}
    params:
      {{- toYaml .Values.controller.serviceMonitor.params | nindent 6 }}
    {{- end }}
    {{- if .Values.controller.serviceMonitor.metrics.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.controller.serviceMonitor.metrics.metricRelabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.controller.serviceMonitor.metrics.relabelings }}
    relabelings:
      {{- toYaml .Values.controller.serviceMonitor.metrics.relabelings | nindent 6 }}
    {{- end }}
  - honorLabels: {{ .Values.controller.serviceMonitor.honorLabels }}
    interval: {{ .Values.controller.serviceMonitor.interval }}
    path: /metrics
    port: ctrl-metrics
    {{- if .Values.controller.serviceMonitor.ctrlMetrics.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.controller.serviceMonitor.ctrlMetrics.metricRelabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.controller.serviceMonitor.ctrlMetrics.relabelings }}
    relabelings:
      {{- toYaml .Values.controller.serviceMonitor.ctrlMetrics.relabelings | nindent 6 }}
    {{- end }}
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "haproxy-ingress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
{{- end }}
