{{- if and .Values.defaultBackend.enabled .Values.rbac.security.enable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "haproxy-ingress.defaultBackend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "haproxy-ingress.defaultBackend.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
