{{- if and .Values.defaultBackend.enabled .Values.rbac.security.enable (semverCompare "< 1.25-0" .Capabilities.KubeVersion.Version) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "haproxy-ingress.defaultBackend.fullname" . }}
    verbs:
      - use
{{- end }}
