{{- if .Values.defaultBackend.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.defaultBackend.service.annotations }}
  annotations:
    {{- toYaml .Values.defaultBackend.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "haproxy-ingress.defaultBackend.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.defaultBackend.service.clusterIP }}
  clusterIP: "{{ .Values.defaultBackend.service.clusterIP }}"
{{- end }}
{{- if .Values.defaultBackend.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.defaultBackend.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.defaultBackend.service.loadBalancerClass }}
  loadBalancerClass: "{{ .Values.defaultBackend.service.loadBalancerClass }}"
{{- end }}
{{- if .Values.defaultBackend.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.defaultBackend.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.defaultBackend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.defaultBackend.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.defaultBackend.service.servicePort }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "haproxy-ingress.defaultBackend.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.defaultBackend.service.type }}"
{{- end }}
