{{- if .Values.rbac.security.enable -}}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  defaultAllowPrivilegeEscalation: false
  allowedCapabilities:
    - SYS_RESOURCE
  defaultAddCapabilities:
    - SYS_RESOURCE
  volumes:
    - configMap
    - secret
  hostNetwork: false
  hostPorts:
  - min: 0
    max: 65535
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  allowedHostPaths:
    - pathPrefix: /etc/haproxy/template
      readOnly: false
{{- end }}
