{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{- if semverCompare ">= 1.22-0" .Capabilities.KubeVersion.Version }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
